language: python
python:
- "2.7"
- "3.5"
- "3.6"
- "3.7"
install:
- cd python
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script:
- nosetests
- flake8 py_vapid
after_success:
    - coverage report --omit py_vapid/main.py
